version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      # Basic Configuration
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=your-secure-password
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      
      # Encryption Key (IMPORTANT: Generate a secure 32-character key)
      - N8N_ENCRYPTION_KEY=your-32-character-encryption-key-here
      
      # Database (PostgreSQL)
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=your-db-password
      
      # API Keys (copy from your current setup)
      - DROPBOX_ACCESS_TOKEN=your-dropbox-access-token
      - GOOGLE_DRIVE_CLIENT_ID=your-google-client-id
      - GOOGLE_DRIVE_CLIENT_SECRET=your-google-client-secret
      - GOOGLE_DRIVE_REFRESH_TOKEN=your-google-refresh-token
      - NOTION_API_KEY=your-notion-api-key
      - OPENAI_API_KEY=your-openai-api-key
      
      # Webhook URL (update with your domain)
      - WEBHOOK_URL=https://your-domain.com
      
      # Security
      - N8N_SECURE_COOKIE=true
      - N8N_SESSION_SECRET=your-session-secret
      
      # Performance
      - N8N_METRICS=true
      - N8N_LOG_LEVEL=info
      
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: n8n-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=your-db-password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  n8n_data:
  postgres_data: